# These are supported funding model platforms

github: DamirPorobic
liberapay: dporobic
patreon: dporobic
open_collective: ksnip
custom: [paypal.me/damirporobic, gofundme.com/f/buy-a-macbook-for-ksnips-cross-platform-support]

