name: ksnip
base: core18 # the base snap is the execution environment for this snap
adopt-info: ksnip
version: "0.1"
grade: stable
confinement: strict

apps:
  ksnip:
    command: ksnip
    common-id: ksnip
    desktop: share/applications/ksnip.desktop
    extensions: [kde-neon]
    plugs:
      - home
      - removable-media

parts:
  ksnip:
    source: .
    plugin: cmake
    parse-info: [share/metainfo/ksnip.appdata.xml]
    after:
      - kimageannotator
    build-snaps:
      - kde-frameworks-5-core18-sdk
    build-packages:
      - libglvnd-dev
      - libx11-dev
    configflags:
      - -DCMAKE_FIND_ROOT_PATH=/snap/kde-frameworks-5-core18-sdk/current;/snap/kimageannotator/current
    override-pull: |
      snapcraftctl pull
      sed -i 's|Icon=.*|Icon=share/pixmaps/ksnip.svg|g' desktop/ksnip.desktop
  kimageannotator:
    source: https://github.com/ksnip/kImageAnnotator.git
    plugin: cmake
    after:
      - kcolorpicker
    configflags:
      - -DCMAKE_FIND_ROOT_PATH=/snap/kde-frameworks-5-core18-sdk/current;/snap/kcolorpicker/current
  kcolorpicker:
    source: https://github.com/ksnip/kColorPicker.git
    plugin: cmake
    configflags:
      - -DCMAKE_FIND_ROOT_PATH=/snap/kde-frameworks-5-core18-sdk/current

